#!/usr/bin/env node
'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');

const indexHtml = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const appJs = fs.readFileSync(path.join(__dirname, '..', 'app.js'), 'utf8');
const uiJs = fs.readFileSync(path.join(__dirname, '..', 'ui.js'), 'utf8');
const stylesCss = fs.readFileSync(path.join(__dirname, '..', 'styles.css'), 'utf8');

assert.ok(indexHtml.includes('id="menuBuddyCareBtn"'), 'menu should expose a Buddy Care+ entry');
assert.ok(indexHtml.includes('data-screen="buddyCare"'), 'HUD should register a buddy care screen');
assert.ok(indexHtml.includes("src: 'src/buddy-care/featureFlags.js'"), 'script loader should include buddy care feature flags');
assert.ok(indexHtml.includes("src: 'src/buddy-care/buddyAssets.js'"), 'script loader should include buddy care buddy assets');
assert.ok(indexHtml.includes("src: 'src/buddy-care/externalTestReadiness.js'"), 'script loader should include the buddy care external test readiness helpers');
assert.ok(indexHtml.includes("src: 'src/buddy-care/monetizationReadiness.js'"), 'script loader should include buddy care monetization readiness helpers');
assert.ok(indexHtml.includes("src: 'src/buddy-care/phaseEngine.js'"), 'script loader should include the phase engine');
assert.ok(indexHtml.includes("src: 'src/buddy-care/taskGenerator.js'"), 'script loader should include the task generator');
assert.ok(indexHtml.includes("src: 'src/buddy-care/riskEngine.js'"), 'script loader should include the risk engine');
assert.ok(indexHtml.includes("src: 'src/buddy-care/trendEngine.js'"), 'script loader should include the trend engine');
assert.ok(indexHtml.includes('id="buddyCareAgeGateAcceptBtn"'), 'age gate accept button should exist');
assert.ok(indexHtml.includes('id="buddyCareOpenPaywallBtn"'), 'buddy care should expose a Care+ preview entry button');
assert.ok(indexHtml.includes('id="buddyCareViewNav"'), 'buddy care should expose an internal view navigation');
assert.ok(indexHtml.includes('data-buddy-care-view="today"'), 'buddy care navigation should expose the today view');
assert.ok(indexHtml.includes('data-buddy-care-view="plants"'), 'buddy care navigation should expose the plants view');
assert.ok(indexHtml.includes('data-buddy-care-view="diary"'), 'buddy care navigation should expose the diary view');
assert.ok(indexHtml.includes('data-buddy-care-view="more"'), 'buddy care navigation should expose the more view');
assert.ok(indexHtml.includes('id="buddyCareTodayView"'), 'buddy care should expose a dedicated today view container');
assert.ok(indexHtml.includes('id="buddyCarePlantsView"'), 'buddy care should expose a dedicated plants view container');
assert.ok(indexHtml.includes('id="buddyCareDiaryView"'), 'buddy care should expose the existing history container');
assert.ok(indexHtml.includes('id="buddyCareMoreView"'), 'buddy care should expose a dedicated more view container');
assert.ok(indexHtml.includes('id="buddyCareSetupForm"'), 'setup form should exist');
assert.ok(indexHtml.includes('id="buddyCarePlantTypeSelect"'), 'setup should expose the plant type select');
assert.ok(indexHtml.includes('id="buddyCarePlantEnvironmentSelect"'), 'setup should expose the environment select');
assert.ok(indexHtml.includes('id="buddyCarePlantStartDateInput"'), 'setup should expose the start date input');
assert.ok(indexHtml.includes('id="buddyCareSummaryCard"'), 'dashboard summary should exist');
assert.ok(indexHtml.includes('id="buddyCareExternalTestIntroCard"'), 'buddy care should expose an external test intro card');
assert.ok(indexHtml.includes('id="buddyCareExternalTestChecklistCard"'), 'buddy care should expose an external test checklist card');
assert.ok(indexHtml.includes('id="buddyCareExternalTestFeedbackCard"'), 'buddy care should expose an external test feedback card');
assert.ok(indexHtml.includes('id="buddyCareExternalTestToolsCard"'), 'buddy care should expose an external test tools card');
assert.ok(indexHtml.includes('id="buddyCareTodayCard"'), 'today card should exist');
assert.ok(indexHtml.includes('id="buddyCareHeroBuddyVisual"'), 'hero should expose a Buddy asset container');
assert.ok(indexHtml.includes('id="buddyCareTodayBuddyVisual"'), 'today hint should expose a Buddy asset container');
assert.ok(indexHtml.includes('id="buddyCarePlantDetailCard"'), 'plants view should expose a dedicated plant detail card');
assert.ok(indexHtml.includes('id="buddyCareDiaryHubCard"'), 'buddy care should expose a central diary view card');
assert.ok(indexHtml.includes('id="buddyCareDailyCheckCard"'), 'daily check card should exist');
assert.ok(indexHtml.includes('id="buddyCareDailyCheckBuddyVisual"'), 'daily check should expose a Buddy asset container');
assert.ok(indexHtml.includes('id="buddyCareDailyCheckForm"'), 'daily check form should exist');
assert.ok(indexHtml.includes('id="buddyCareDailyCheckMoistureSelect"'), 'daily check should expose the medium field');
assert.ok(indexHtml.includes('id="buddyCareDailyCheckLeafStateSelect"'), 'daily check should expose the leaf field');
assert.ok(indexHtml.includes('id="buddyCareDailyCheckPestsVisibleSelect"'), 'daily check should expose the pests field');
assert.ok(indexHtml.includes('id="buddyCarePlantList"'), 'plant list should exist');
assert.ok(indexHtml.includes('id="buddyCareAddPlantBtn"'), 'add plant button should exist');
assert.ok(indexHtml.includes('id="buddyCareMockUpgradeBtn"'), 'mock entitlement button should exist');
assert.ok(indexHtml.includes('id="buddyCareSeasonPassCard"'), 'season pass preview card should exist');
assert.ok(indexHtml.includes('id="buddyCareSeasonPassActivateBtn"'), 'season pass should expose a mock activation button');
assert.ok(indexHtml.includes('id="buddyCareSeasonPassFeatureList"'), 'season pass preview should expose a feature list container');
assert.ok(indexHtml.includes('id="buddyCareSeasonPassStatusNote"'), 'season pass preview should expose a checkout readiness note');
assert.ok(indexHtml.includes('id="buddyCareFreeHintBody"'), 'free hint should expose a dynamic upgrade reason body');
assert.ok(indexHtml.includes('id="buddyCareActivationCard"'), 'buddy care should expose an activation onboarding card');
assert.ok(appJs.includes("createPassiveScreenModule('buddyCare')"), 'app runtime should register the passive buddy care screen');
assert.ok(appJs.includes('function renderBuddyCareScreen()'), 'app should render the buddy care placeholder screen');
assert.ok(appJs.includes('function setActiveBuddyCareView(view, options = {})'), 'app should expose a local buddy care view-state setter');
assert.ok(appJs.includes('function setBuddyCarePlantFilter(filterValue = \'all\')'), 'app should expose normalized plant filters');
assert.ok(appJs.includes('function setBuddyCareHistoryMode(mode = \'timeline\')'), 'app should expose timeline and trends modes');
assert.ok(appJs.includes('function renderBuddyCareViewNavigation(ageGateAccepted)'), 'app should render the buddy care internal navigation');
assert.ok(appJs.includes('function openBuddyCarePlantDetails(plantId, section = \'overview\')'), 'app should expose a dedicated plant detail opener');
assert.ok(appJs.includes('function renderBuddyCarePlantDetailCard(cards, ageGateAccepted)'), 'app should render the dedicated plant detail card');
assert.ok(appJs.includes('function renderBuddyCareDiaryHubCard(cards, ageGateAccepted)'), 'app should render the central diary view');
assert.ok(appJs.includes('function submitBuddyCarePlantSetup()'), 'app should expose the setup submit handler');
assert.ok(appJs.includes('function submitBuddyCareDailyCheck()'), 'app should expose the daily check submit handler');
assert.ok(appJs.includes('function submitBuddyCareDiaryEntry(plantId, formNode)'), 'app should expose the diary submit handler');
assert.ok(appJs.includes('function deleteBuddyCareDiaryEntry(entryId)'), 'app should expose the diary delete handler');
assert.ok(appJs.includes('function renderBuddyCareHeroVisual(summary = null, activeView = \'today\', options = {})'), 'app should render the buddy care hero visual per active view');
assert.ok(appJs.includes('function getBuddyCareRiskApi()'), 'app should expose the buddy care risk engine bridge');
assert.ok(appJs.includes('function getBuddyCareTrendApi()'), 'app should expose the buddy care trend engine bridge');
assert.ok(appJs.includes('function getBuddyCareDailyCheckBuddyPresentation('), 'app should map daily check statuses to Buddy visuals');
assert.ok(appJs.includes('function renderBuddyCarePlantList(cards)'), 'app should render the enriched plant list');
assert.ok(appJs.includes('function renderBuddyCareMiniHistory(card)'), 'app should render the buddy care mini history card');
assert.ok(appJs.includes('function renderBuddyCareWeeklyReview(card)'), 'app should render the buddy care weekly review card');
assert.ok(appJs.includes("function openBuddyCarePaywallMock(source = '')"), 'app should expose the buddy care paywall preview opener');
assert.ok(appJs.includes('function renderBuddyCareSeasonPassPreview()'), 'app should render the centralized season pass preview data');
assert.ok(appJs.includes('function startBuddyCareExternalTest()'), 'app should expose the external test intro CTA handler');
assert.ok(appJs.includes('function getBuddyCareExternalTestSummary()'), 'app should expose a local external test summary helper');
assert.ok(appJs.includes('function resetBuddyCareTestData()'), 'app should expose a buddy-care-specific test reset handler');
assert.ok(appJs.includes('function trackBuddyCareConversionIntent('), 'app should expose a buddy care conversion intent tracker');
assert.ok(appJs.includes('function closeBuddyCarePaywallMock()'), 'app should expose the buddy care paywall preview closer');
assert.ok(appJs.includes('function buildBuddyCareActivationOnboardingViewModel('), 'app should build the care+ activation onboarding state');
assert.ok(appJs.includes('function runBuddyCareActivationPrimaryAction('), 'app should expose the activation onboarding CTA handler');
assert.ok(appJs.includes('function buildBuddyCareDashboardViewModel()'), 'app should build the buddy care dashboard model');
assert.ok(appJs.includes('function flushBuddyCareDeferredMenuDialog()'), 'app should defer simulator dialogs while buddy care stays active');
assert.ok(appJs.includes("reason: 'confirm_pending'"), 'diary deletion should wait for a confirmation dialog');
assert.ok(uiJs.includes('window.__gsOpenBuddyCare'), 'ui wiring should delegate into the buddy care runtime');
assert.ok(uiJs.includes('window.__gsSetActiveBuddyCareView'), 'ui wiring should support internal view switches');
assert.ok(uiJs.includes('window.__gsSetBuddyCarePlantFilter'), 'ui wiring should support plant status filtering');
assert.ok(uiJs.includes('window.__gsSetBuddyCareHistoryMode'), 'ui wiring should support history mode changes');
assert.ok(uiJs.includes('window.__gsOpenBuddyCarePlantDetails'), 'ui wiring should support dedicated plant detail opens');
assert.ok(uiJs.includes('window.__gsSubmitBuddyCareDiaryHubEntry'), 'ui wiring should support diary hub submissions');
assert.ok(uiJs.includes('window.__gsOpenBuddyCarePaywallMock'), 'ui wiring should support opening the paywall preview');
assert.ok(uiJs.includes("window.__gsOpenBuddyCarePaywallMock('header')"), 'ui wiring should tag header paywall opens');
assert.ok(uiJs.includes("window.__gsOpenBuddyCarePaywallMock('mock-card')"), 'ui wiring should tag mock-card paywall opens');
assert.ok(uiJs.includes('window.__gsRunBuddyCareActivationPrimaryAction'), 'ui wiring should support activation onboarding CTAs');
assert.ok(uiJs.includes('window.__gsToggleBuddyCarePlantDetails'), 'ui wiring should support detail toggles');
assert.ok(uiJs.includes('window.__gsSubmitBuddyCareDailyCheck'), 'ui wiring should support daily check submission');
assert.ok(uiJs.includes('window.__gsSubmitBuddyCareDiaryEntry'), 'ui wiring should support diary submission');
assert.ok(uiJs.includes('window.__gsDeleteBuddyCareDiaryEntry'), 'ui wiring should support diary deletion');
assert.ok(uiJs.includes('window.__gsSubmitBuddyCareExternalTestFeedback'), 'ui wiring should support external test feedback submission');
assert.ok(uiJs.includes('window.__gsResetBuddyCareTestData'), 'ui wiring should support a buddy-care-only test reset');
assert.ok(uiJs.includes("event.target.closest('[data-buddy-care-diary-form]')"), 'ui wiring should capture diary submits from the dedicated plant detail view');
assert.ok(stylesCss.includes('.buddy-care-hero-asset'), 'buddy care should define a hero asset style');
assert.ok(stylesCss.includes('.buddy-care-nav'), 'buddy care should style the internal navigation');
assert.ok(stylesCss.includes('.buddy-care-nav-btn'), 'buddy care should style the internal navigation buttons');
assert.ok(stylesCss.includes('.buddy-care-view'), 'buddy care should style dedicated view containers');
assert.ok(stylesCss.includes('.buddy-care-buddy-asset'), 'buddy care should define a bubble asset style');
assert.ok(stylesCss.includes('.buddy-care-empty-state--buddy'), 'buddy care should style the empty state with a Buddy visual');
assert.ok(stylesCss.includes('.buddy-care-diary-form'), 'buddy care should style the diary form');
assert.ok(stylesCss.includes('.buddy-care-diary-entry'), 'buddy care should style diary timeline entries');
assert.ok(stylesCss.includes('.buddy-care-risk-badge'), 'buddy care should style the risk badge');
assert.ok(stylesCss.includes('.buddy-care-today-head'), 'buddy care should style the prioritized today layout');
assert.ok(stylesCss.includes('.buddy-care-today-focus'), 'buddy care should style the single-focus today hint');
assert.ok(stylesCss.includes('.buddy-care-today-trend'), 'buddy care should style the today trend hint');
assert.ok(stylesCss.includes('.buddy-care-today-weekly-focus'), 'buddy care should style the weekly focus hint in today view');
assert.ok(stylesCss.includes('.buddy-care-buddy-note--trend'), 'buddy care should style the diary trend card');
assert.ok(stylesCss.includes('.buddy-care-buddy-note--weekly'), 'buddy care should style the weekly review card');
assert.ok(stylesCss.includes('.buddy-care-buddy-note--seasonpass'), 'buddy care should style the season pass Buddy note');
assert.ok(stylesCss.includes('.buddy-care-buddy-note--activation'), 'buddy care should style the activation onboarding Buddy note');
assert.ok(stylesCss.includes('.buddy-care-history-card'), 'buddy care should style the mini history card');
assert.ok(stylesCss.includes('.buddy-care-weekly-card'), 'buddy care should style the weekly review container');
assert.ok(stylesCss.includes('.buddy-care-segment-nav'), 'buddy care should style the plant detail segments');
assert.ok(stylesCss.includes('.buddy-care-filter-row'), 'buddy care should style diary filters');
assert.ok(stylesCss.includes('.buddy-care-plant-profile-card'), 'buddy care should style profile-led plant cards');
assert.ok(stylesCss.includes('.buddy-care-history-switch'), 'buddy care should style the history mode switch');
assert.ok(stylesCss.includes('.buddy-care-seasonpass-card'), 'buddy care should style the season pass preview card');
assert.ok(stylesCss.includes('.buddy-care-test-checklist'), 'buddy care should style the external test checklist');
assert.ok(stylesCss.includes('.buddy-care-view[hidden]'), 'buddy care should fully remove inactive views from layout');
assert.ok(stylesCss.includes('.buddy-care-nav[hidden]'), 'buddy care should fully remove the hidden internal nav from layout');
assert.match(stylesCss, /\.buddy-care-screen\s*\{[\s\S]*overflow-y:\s*auto;[\s\S]*-webkit-overflow-scrolling:\s*touch;/, 'buddy care screen should use a dedicated vertical scroll container');
assert.match(stylesCss, /\.buddy-care-screen\s*\{[\s\S]*min-height:\s*0;[\s\S]*height:\s*100%;/, 'buddy care screen should be constrained to the HUD height');
assert.ok(indexHtml.includes('Testzugang aktivieren'), 'buddy care shell should use test access wording for the premium preview');
assert.ok(indexHtml.includes('Heute wichtig'), 'buddy care shell should keep today as the primary dashboard anchor');
assert.ok(!indexHtml.includes('Technisches Fundament'), 'buddy care shell should avoid internal architecture wording');
assert.ok(!indexHtml.includes('Phase 5 ist bereit'), 'buddy care shell should avoid phase rollout wording');
assert.ok(!indexHtml.includes('MVP 0.1'), 'buddy care shell should avoid MVP wording');
assert.ok(!indexHtml.includes('Mock freischalten'), 'buddy care shell should avoid mock unlock wording');
assert.ok(!indexHtml.includes('Testmodus:'), 'buddy care shell should avoid raw test mode labels in visible product copy');

console.log('buddy-care-ui-shell.test.js passed');
